### ISSUE TITLE
Tab scroll buttons texture looks of with opengl enabled

### ISSUE THREAD

**Issue by deathaxe** [jwortmann/brackets-theme#1]
Might be a core bug, but some image paddings need to be defined a bit different to make them appear well if ST is run with opengl hardware accelleration. Those look fine with `hardware_accelleration: "none"`

![grafik](https://user-images.githubusercontent.com/16542113/126862370-6b30f77b-9987-4e30-b83b-6a7c81fcdb41.png)

- ST 4112
- hardware_accelleration: opengl
- Windows 10 21H1
- 4k 150%

**Comment by jwortmann** [comment]
Fixed in e232af213f8fad023c9c156476483842ee61058a.
